[[redirects]]
    from = "/api/*"
    to = "http://43.202.14.234:8080/:splat"
    status = 200
    force = true

[[redirects]]
    from = "/api/tweets"
    to = "http://43.202.14.234:8080/tweets"
    status = 201
    force = true

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200