[[redirects]]
    from = "/api/*"
    to = "http://43.202.14.234:8080/:splat"
    status = 200
    force = true
    method = ["GET", "POST", "DELETE"]

[[redirects]]
    from = "/"
    to = "/index.html"
    status = 200